spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: springBoot
    password: admin
    url: jdbc:mysql://localhost:3306/test1
    username: root
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: "update\t"
    properties:
      hibernate:
        Dilect: org.hibernate.dialect.MySQL5Dialect
      